---
language: ruby
rvm:
- 1.9.3
- 2.0.0
- 2.1.1
- 2.1.2
services:
- redis-server
notifications:
  email: false
  campfire:
    rooms:
    - secure: ! 'Mul3ljnfdVyNDkAkCtwB+YAx3n+2JMpQqJD2iCNrz7axnvX24NzcnGUzqLgK

        CGOLRLc95MxDiRFnTChoorIEs7ozlYb0xrJp5AGKLBc1B+r1P9djg0lxDx36

        tHIYY5K1/9cKbGncm3pwRDaqkI3kffFpwQ5b/IYXH/3S9RYaXCM='
